### ISSUE TITLE
Rename repo to "community"

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/people#78]
Between #71 and #72, we may or may not assign a DNS subdomain to this repo. If we turn down #71, I suggest renaming this repository to `community` so the published URL becomes `fossrit.github.io/community`. I think this is more memorable and user-friendly, and also loosely supports the overall goal of #72 in integrating the web presence of the two Jekyll sites.

**Comment by 10eMyrT** [comment]
From my point of view, a subdomain would not be necessary. Leveraging the advantage of github.io is better. I also support renaming, and `fossrit.github.io/community` or `fossrit.github.io/people` are valid choices. I suggest we maintain #72 and continue on finding ways to bring fossrit website and foss-profile closer.

**Comment by jwflory** [comment]
It has been done! I liked @10eMyrT's suggestion and @wilfriedE concurred. So `FOSSRIT/people` it is. Closing as complete. :clapper:
